modLoader = "javafml"
loaderVersion = "[2,)"
license = "AGPL-3.0-only"

[[mods]]
modId = "soul_fire_burning"
version = "${version}"
displayName = "Soul Fire Burning"
authors = "ENC_Euphony"
description = '''
Makes soul fire burn with blue flames and optional enhanced damage.
'''
iconFile = "icon.png"

[[mixins]]
config = "soul_fire_burning.mixins.json"

[[dependencies.soul_fire_burning]]
modId = "neoforge"
type = "required"
versionRange = "[26.2-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soul_fire_burning]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,27)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soul_fire_burning]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.9,)"
ordering = "NONE"
side = "BOTH"
